version: '3.8'

services:
  agilent-support-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Backend API
      - "3000:3000"  # Frontend
    volumes:
      - ./logs:/app/logs
      - ./feedback_data:/app/feedback_data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
